# Plugin Definition below. This is essentially a valid helm values file that will be merged
# with the other vcluster values during vcluster create or helm install.
plugin:
  cert-manager:
    image: ghcr.io/loft-sh/vcluster-generic-crd-plugin:latest
    imagePullPolicy: IfNotPresent
    rbac:
      role:
        extraRules:
          - apiGroups: ["cert-manager.io"]
            resources: ["issuers", "certificates"]
            verbs: ["create", "delete", "patch", "update", "get", "list", "watch"]
      clusterRole:
        extraRules:
          - apiGroups: ["apiextensions.k8s.io"]
            resources: ["customresourcedefinitions"]
            verbs: ["get", "list", "watch"]
    env:
      - name: CONFIG
        value: |-
          version: v1beta1
          mappings:
            - fromVirtualCluster:
                # CRD for the apiVersion+Kind is implicitly copied to the virtual cluster
                apiVersion: cert-manager.io/v1
                kind: Issuer
                patches:
                  - op: rewriteName
                    path: spec.ca.secretName
                    sync:
                      secret: true
                reversePatches:
                  - op: copyFromObject
                    fromPath: status
                    path: status
            - fromVirtualCluster:
                apiVersion: cert-manager.io/v1
                kind: Certificate
                patches:
                  - op: rewriteName
                    path: spec.issuerRef.name
                  - op: rewriteName
                    path: spec.keystores.pkcs12.passwordSecretRef.name
                  - op: rewriteName
                    path: spec.secretName
                reversePatches:
                  - op: copyFromObject
                    fromPath: status
                    path: status
                syncBack:
                  - kind: Secret
                    apiVersion: v1
                    selectors:
                      - name:
                          rewrittenPath: spec.secretName
                    patches:
                      - op: rewriteName
                        path: metadata.annotations['cert-manager.io/certificate-name']
                      - op: rewriteName
                        path: metadata.annotations['cert-manager.io/issuer-name']
